---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Install in your local dev environment
# > pip install --upgrade --user pre-commit
# Enable the hooks for this repo
# > pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files  # Prevents giant files from being committed
      # - id: check-json               # Check that JSON files are valid
      - id: check-merge-conflict     # Check merge conflict strings
      - id: check-symlinks           # Ensure symlinks have a valid target
      - id: check-toml               # Ensure toml files are valid
      - id: check-xml                # Check that XML files are valid
      - id: end-of-file-fixer        # File is empty or ends with one newline
      - id: fix-byte-order-marker    # Forbid utf-8 byte order marker
      - id: trailing-whitespace      # Trims trailing whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.37.1"
    hooks:
      - id: yamllint
        args: ["-c", "./.github/.yamllint.yaml", "--strict"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.45.0"
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".github/markdownlint-config.yaml"]
        exclude: |
          (?x)^(
                .github/pull_request_template.md |
                .github/prompts/.*\.md |
                .specify/templates/.*\.md
            )$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: shellcheck
        exclude: |
          (?x)^(
                .specify/scripts/bash/.*
            )$

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: "41.135.5"
    hooks:
      - id: renovate-config-validator

  - repo: https://gitlab.com/bmares/check-json5
    rev: "v1.0.0"
    hooks:
      # Check that JSON files are valid JSON5
      - id: check-json5
